# Generated by Django 4.1.5 on 2023-02-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Submit', 'Submit'), ('Cancel', 'Cancel')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.action')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.form')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.input')),
            ],
        ),
    ]
