# Generated by Django 4.1.5 on 2023-02-20 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_action_form_input_formstructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
