# Generated by Django 4.1.5 on 2023-02-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_alter_form_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstructure',
            name='input_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
