# Generated by Django 4.1.5 on 2023-02-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_formstructure_input_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.formstructure')),
            ],
        ),
    ]
